version: '3.8'

services:
  database_server:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network
      - dokploy-network

  web:
    build: .
    container_name: django_app
    restart: always
    # USAR ENTRYPOINT PARA FORÇAR A EXECUÇÃO DO SCRIPT
    entrypoint:
      - sh
      - -c
      - |
        echo "--> INICIANDO SCRIPT DE DEPLOY..."
        echo "--> Testando resolucao DNS para database_server..."
        
        # Loop em Python puro para testar DNS e Conexão TCP
        python -c "
        import socket, time, sys
        host = 'database_server'
        port = 5432
        
        # 1. Teste de DNS
        while True:
            try:
                ip = socket.gethostbyname(host)
                print(f'--> DNS OK: {host} resolve para {ip}')
                break
            except socket.gaierror:
                print('--> Aguardando DNS resolver database_server...')
                time.sleep(2)
        
        # 2. Teste de TCP
        print(f'--> Testando conexao TCP em {host}:{port}...')
        while True:
            try:
                with socket.create_connection((host, port), timeout=3):
                    print('--> CONEXAO TCP SUCESSO!')
                    break
            except (OSError, ConnectionRefusedError) as e:
                print(f'--> Porta fechada ou recusada ({e}). Tentando novamente...')
                time.sleep(2)
        "
        
        echo "--> Iniciando comandos Django..."
        python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://${USER_DB}:${PASSWORD_DB}@database_server:5432/${POSTGRES_DB}
    depends_on:
      database_server:
        condition: service_healthy
    networks:
      - app_network
      - dokploy-network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
  dokploy-network:
    external: true
